version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./client/public:/usr/share/nginx/html
    depends_on:
      - localstack

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    restart: always
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=${DEFAULT_REGION}
    ports:
      - 4566:4566
    volumes:
      - ./localstack:/tmp/localstack
